version: '3'
services:
  app:
    container_name: app
    build:
      context: . 
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./app:/usr/src/app
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
  database:
    container_name: postgresql
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports: 
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: master

  storybook:
    container_name: storybook
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./app:/usr/src/app
    command: sh -c "npm run storybook"
    ports: 
      - 6006:6006

